######################################
# Reusable steps should be added here.
######################################
install-dependencies: &install-dependencies
  run:
    name: Install Dependencies
    command: |
      cd "${LOCATION:-.}"
      # pip installing virtualenv in Python 3 will be a no-op
      pip install virtualenv
      virtualenv .venv
      . .venv/bin/activate
      make install-deps
lint: &lint
  run:
    name: Run Linters
    command: |
      cd "${LOCATION:-.}"
      . .venv/bin/activate
      make lint
check-version-bump: &check-version-bump
  run:
    name: Check Python package version
    command: |
      cd "${LOCATION:-.}"
      bin/diffcheck
test: &test
  run:
    name: Run Tests
    command: |
      cd "${LOCATION:-.}"
      . .venv/bin/activate
      make test

###########
# Workflows
###########
version: 2
workflows:
  version: 2

  build_all:
    jobs:
      - build
      - build-py2

###################
# Job Definitions
###################
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: dep-{{ checksum "deps/dev-requirements.txt" }}-{{ checksum "deps/requirements.txt" }}
      - <<: *install-dependencies
      - save_cache:
          paths:
            - .venv
          key: dep-{{ checksum "deps/dev-requirements.txt" }}-{{ checksum "deps/requirements.txt" }}
      - setup_remote_docker
      - <<: *lint
      - <<: *check-version-bump
      - <<: *test

  build-py2:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - restore_cache:
          key: dep-{{ checksum "deps/dev-requirements-py2.txt" }}-{{ checksum "deps/requirements-py2.txt" }}
      - <<: *install-dependencies
      - save_cache:
          paths:
            - .venv
          key: dep-{{ checksum "deps/dev-requirements-py2.txt" }}-{{ checksum "deps/requirements-py2.txt" }}
      - setup_remote_docker
      - <<: *test
